---
- name: "Create Backend directory."
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "unarchive backend files"
  become: true
  unarchive:
    src:  artifact.tar.gz
    dest:  /home/ubuntu


- name: "installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i
    



- name: "start node app with PM2"
  become: true
  shell: |
    cd  /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js

 

