---
  - name: "create beckend directory"
    file:
       path: ~/backend-app
       state: directory

  - name: "unarchive backend directory"
    unarchive:
        src: artifact.tar.gz
        dest: ~/backend-app
   

  - name: "installing Node Dependencies"
    shell: |
      cd ~/backend-app
      npm i

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "Executing node app with pm2"
    become: true
    shell: |
      cd ~/backend-app/dist
      pm2 stop default
      pm2 start -f main.js
    register: execute_node


 
  - name: "configure pm2 to start as aservice"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

    
