---


- name: "Create Backend directory."
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "unarchive backend files"
  become: true
  unarchive:
    src:   ~/project/artifact.tar.gz
    dest:  /home/ubuntu/backend


- name: "installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i
    



- name: "start node app with PM2"
  become: true
  shell: |
    cd  /home/ubuntu/backend/dist
    pm2 kill
    pm2 start main.js

 

