---
- name: Create Backend directory.
  file:
  copy:
    path: ~/backend
    state: directory

- name: unarchive backend directory
  unarchive:
  src: artifact.tar.gz
  dest:  ~/backend

- name: installing node dependecies
  shell: |
    cd ~/backend
    npm i


- name: ewxecuting node app with PM2
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js

  args:
    chdir: ~/backend/dist
  environment:
      NODE_ENV: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  

