---
  - name: "create beckend directory"
    file:
       pathe: ~/backend
       state: directory

  - name: "unarchive backend directory"
    unarchive:
        src: artifact.tar.gz
        dest: ~/backend
   

  - name: "installing Node Dependencies"
    shell: |
      cd ~/backend-app
      npm i

    

  - name: "Executing node app with pm2"
    shell: |
      cd ~/backend-app/dist
      pm2 stop default
      pm2 start main.js
     
    register: execute_node


 
  - name: "configure pm2 to start as aservice"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

    
