---
- name: copy dist backend folder to ec2 server
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/UDA-APP/artifact.tar.gz

- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu/UDA-APP
    tar xvzf artifact.tar.gz -C .


- name: start server
  become: true
  shell: |
    cd /home/ubuntu/UDA-APP
    pm2 start npm --name UDA-APP -- start
