---
- name: "Create Backend directory."
  file:
    path: ~/backend_app
    state: directory

- name: "copy backend directory"
  copy:
    src:  ~/project/.circleci/ansible/roles/deploy/files
    dest:  ~/backend_app
    remote_src: true

- name: "installing Node Dependencies"
  command: |
      cd ~/backend-app
      npm i
    

- name: "delete all pm2 process"
  command: |
     pm2 delete all
  ignore_errors: true


- name: "start node app with PM2"
  command: |
    pm2 start ~/backend_app/dist/main.js -f
  ignore_errors: true

 
  environment:
      NODE_ENV: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  

